##trabajo numero 3 realizar figuras 
print("* * * * * * * * * *")
print("*                 *")
print("*                 *")
print("*                 *")
print("*                 *")
print("*                 *")
print("*                 *")
print("*                 *")
print("*                 *")
print("* * * * * * * * * *")